notifications:
  email: false
language: csharp
solution: Unmanaged.sln
mono: none
dotnet: 2.1.300
script:
  - dotnet restore
  - dotnet test tests/Unmanaged.Tests/Unmanaged.Tests.csproj -c Release -f "netcoreapp2.1"