notifications:
  email: false
language: csharp
solution: UNM.sln
mono: none
dotnet: 2.1.4
script:
  - dotnet restore
  - dotnet test test/Unmanaged.Test/Unmanaged.Test.csproj -c Release -f "netcoreapp2.0"