version: 1.0.0.{build}
image: Visual Studio 2017

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

before_build:
  - cmd: dotnet --version
  
build_script:
- cmd: deploy.cmd